### PR TITLE
Fix bugs for Edit and Match and addSession

### LINKED ISSUE #282: [PE-D][Tester D] Incorrect error message for match command
Command tested: `match test1 test2`

Expected: Invalid value error (test1 and test2 are not positive integers)
Actual: Error message, invalid command format (Format error)

Image
Error message is not specific to the issue that is present in the command, and can misguide users.

Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by tevyntan**
fixed #282 
 #280 #286 
#283 #287 #288

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -150,6 +150,10 @@ private static void ensureStillCompatibleOrThrow(Person edited, Person counterpa
             problems.append("- Level mismatch: ")
                     .append(student.getLevel()).append(" vs ").append(tutor.getLevel()).append("\n");
         }
+        if (!student.getPrice().overlaps(tutor.getPrice())) {
```
Comment (RagingRogue) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Good job tevyn for handling this condition
